/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interviewer;

import java.awt.Font;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sambhav Kanishka
 */
public class Screen extends javax.swing.JFrame {

    static int ms=0, sec=0,mins=0,hrs=0;
    boolean st = false;
    ServerSocket ss =new ServerSocket(6668);//, sms = new ServerSocket(6667);
    Socket s = ss.accept();//,sm = sms.accept();
    DataOutputStream dout, doutm; DataInputStream dis; String str;
    //ServerSocket ss;
    //static{
//        try {
//           //s = new Socket("192.168.137.1",6666);
//            s = new Socket("172.29.44.250",6666);     
//        } catch (IOException ex) {
//            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
//        }
  //      System.out.println("inside static");
    //}
    /**
     * Creates new form Screen
     * @throws java.io.IOException
     */
    public Screen() throws IOException {
        initComponents();
        dout=new DataOutputStream(s.getOutputStream());
       // doutm = new DataOutputStream(sm.getOutputStream());
        Mthread t1 = new Mthread();
        t1.start();
//        try {
//           //s = new Socket("192.168.137.1",6666);
//            s = new Socket("172.29.44.250",6669);     
//        } catch (IOException ex) {
//            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        question = new javax.swing.JTextField();
        studentName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        message_display_area = new javax.swing.JTextArea();
        message_area = new javax.swing.JTextField();
        send_btn = new javax.swing.JButton();
        compile_btn = new javax.swing.JButton();
        run_btn = new javax.swing.JButton();
        select_language = new javax.swing.JComboBox<>();
        select_font_size = new javax.swing.JComboBox<>();
        select_font_style = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        input_text_tab = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        output_text_tab = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        notes_text = new javax.swing.JTextField();
        save_notes_btn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        code_editor = new javax.swing.JEditorPane();
        hours = new javax.swing.JLabel();
        minutes = new javax.swing.JLabel();
        seconds = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        menu_bar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question.setText("Question");
        question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionActionPerformed(evt);
            }
        });

        studentName.setEditable(false);
        studentName.setText("Student's Name");
        studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameActionPerformed(evt);
            }
        });

        message_display_area.setEditable(false);
        message_display_area.setColumns(20);
        message_display_area.setRows(5);
        jScrollPane2.setViewportView(message_display_area);

        message_area.setText("Type your message");
        message_area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                message_areaMouseClicked(evt);
            }
        });
        message_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                message_areaActionPerformed(evt);
            }
        });

        send_btn.setText("Send");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });

        compile_btn.setText("Compile");

        run_btn.setText("Run");
        run_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_btnActionPerformed(evt);
            }
        });

        select_language.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "C++ 14", "Java", "Python", " " }));

        select_font_size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        select_font_size.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                select_font_sizeItemStateChanged(evt);
            }
        });
        select_font_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_font_sizeActionPerformed(evt);
            }
        });

        select_font_style.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Times New Roman", "Abadi MT Condensed Extra Bold", "Abadi MT Condensed Light", "Academy Engraved LET", "Al Bayan", "American Typewriter", "Andale Mono", "Apple Casual", "Apple Chancery", "Apple LiGothic", "Apple LiSung", "Apple Symbols", "AppleGothic", "AppleMyungjo", "Arial", "Arial Black", "Arial Hebrew", "Arial Narrow", "Arial Rounded MT Bold", "Ayuthaya", "Baghdad", "Bank Gothic", "Baskerville", "Baskerville Old Face", "Batang", "Bauhaus 93", "Bell MT", "Bernard MT Condensed", "BiauKai", "Big Caslon", "Bitstream Vera Sans", "Bitstream Vera Sans Mono", "Bitstream Vera Serif", "Blackmoor LET", "BlairMdITC TT", "Bodoni Ornaments ITC TT", "Bodoni SvtyTwo ITC TT", "Bodoni SvtyTwo OS ITC TT", "Bodoni SvtyTwo SC ITC TT", "Book Antiqua", "Bookman Old Style", "Bordeaux Roman Bold LET", "Bradley Hand ITC TT", "Braggadocio", "Britannic Bold", "Brush Script MT", "Calisto MT", "Century", "Century Gothic", "Century Schoolbook", "Chalkboard", "Charcoal CY", "Cochin", "Colonna MT", "Comic Sans MS", "Cooper Black", "Copperplate", "Copperplate Gothic Bold", "Copperplate Gothic Light", "Corsiva Hebrew", "Courier", "Courier New", "Cracked", "Curlz MT", "DecoType Naskh", "Desdemona", "Devanagari MT", "Dialog", "DialogInput", "Didot", "Edwardian Script ITC", "Engravers MT", "Euphemia UCAS", "Eurostile", "Footlight MT Light", "Futura", "Garamond", "GB18030 Bitmap", "Geeza Pro", "Geneva", "Geneva CY", "Georgia", "Gill Sans", "Gill Sans Ultra Bold", "Gloucester MT Extra Condensed", "Goudy Old Style", "Gujarati MT", "Gulim", "Gurmukhi MT", "Haettenschweiler", "Handwriting - Dakota", "Harrington", "Hei", "Helvetica", "Helvetica CY", "Helvetica Neue", "Herculanum", "Hiragino Kaku Gothic Pro", "Hiragino Kaku Gothic Std", "Hiragino Maru Gothic Pro", "Hiragino Mincho Pro", "Hoefler Text", "Impact", "Imprint MT Shadow", "InaiMathi", "Jazz LET", "Kai", "Kino MT", "Krungthep", "KufiStandardGK", "LiHei Pro", "LiSong Pro", "Lucida Blackletter", "Lucida Bright", "Lucida Calligraphy", "Lucida Fax", "Lucida Grande", "Lucida Handwriting", "Lucida Sans", "Lucida Sans Typewriter", "Marker Felt", "Matura MT Script Capitals", "Mistral", "Modern No. 20", "Mona Lisa Solid ITC TT", "Monaco", "Monospaced", "Monotype Corsiva", "Monotype Sorts", "MS Gothic", "MS Mincho", "MS PGothic", "MS PMincho", "Mshtakan", "MT Extra", "Nadeem", "New Peninim MT", "News Gothic MT", "Onyx", "OpenSymbol", "Optima", "Osaka", "Palatino", "Papyrus", "Party LET", "Perpetua Titling MT", "Plantagenet Cherokee", "Playbill", "PMingLiU", "PortagoITC TT", "Princetown LET", "Raanana", "Rockwell", "Rockwell Extra Bold", "SansSerif", "Santa Fe LET", "Sathu", "Savoye LET", "SchoolHouse Cursive B", "SchoolHouse Printed A", "Serif", "Silom", "SimSun", "Skia", "Snell Roundhand", "Stencil", "STFangsong", "STHeiti", "STKaiti", "Stone Sans ITC TT", "Stone Sans Sem ITC TT", "STSong", "Symbol", "Synchro LET", "Tahoma", "Thonburi", "Times", "Times New Roman", "Trebuchet MS", "Type Embellishments One LET", "Verdana", "Webdings", "Wide Latin", "Wingdings", "Wingdings 2", "Wingdings 3", "Zapf Dingbats", "Zapfino" }));
        select_font_style.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                select_font_styleItemStateChanged(evt);
            }
        });
        select_font_style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_font_styleActionPerformed(evt);
            }
        });

        input_text_tab.setColumns(20);
        input_text_tab.setRows(5);
        jScrollPane4.setViewportView(input_text_tab);

        jTabbedPane1.addTab("Input", jScrollPane4);

        output_text_tab.setEditable(false);
        output_text_tab.setColumns(20);
        output_text_tab.setRows(5);
        jScrollPane5.setViewportView(output_text_tab);

        jTabbedPane1.addTab("Output", jScrollPane5);

        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane3.setViewportView(notes);

        notes_text.setEditable(false);
        notes_text.setText("Notes");
        notes_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notes_textActionPerformed(evt);
            }
        });

        save_notes_btn.setText("Save");
        save_notes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_notes_btnActionPerformed(evt);
            }
        });

        code_editor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                code_editorKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(code_editor);

        hours.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hours.setText("00");

        minutes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        minutes.setText("00");

        seconds.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        seconds.setText("00");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Stop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        menu_bar.add(jMenu1);

        jMenu2.setText("Edit");
        menu_bar.add(jMenu2);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(question, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(compile_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(run_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(select_font_style, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_font_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(message_area)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(send_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seconds, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(save_notes_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notes_text)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(minutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message_area, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(send_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(compile_btn)
                                .addComponent(run_btn)
                                .addComponent(select_language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(select_font_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(notes_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(select_font_style, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save_notes_btn))
                    .addComponent(jTabbedPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void run_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_run_btnActionPerformed

    private void save_notes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_notes_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_notes_btnActionPerformed

    private void studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
//         TODO add your handling code here:
        String string = (String)message_area.getText();
        try {
            dout.writeUTF(string);
            dout.writeInt(1);
            dout.flush();
            message_display_area.setText(message_display_area.getText() + "\n" + "You: "+string);
            message_area.setText("");
            
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_send_btnActionPerformed

    private void notes_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notes_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notes_textActionPerformed

    private void message_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_message_areaActionPerformed
        // TODO add your handling code here:
       String string = (String)message_area.getText();
        try {
            dout.writeUTF(string);
            dout.writeInt(1);
            dout.flush();
            message_display_area.setText(message_display_area.getText() + "\n" + "You: "+string);
            message_area.setText("");
            
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_message_areaActionPerformed

    private void select_font_styleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_font_styleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_font_styleActionPerformed

    private void select_font_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_font_sizeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_select_font_sizeActionPerformed

    private void code_editorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_code_editorKeyPressed
        // TODO add your handling code here:
        try{    
//System.out.println("here");
dout.writeUTF(code_editor.getText());
dout.writeInt(0);
//System.out.println(code_editor.getText());
dout.flush();    
}
        catch(Exception e){System.out.println(e + "exception occured|| fatal exception");}
    }//GEN-LAST:event_code_editorKeyPressed

    private void select_font_sizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_select_font_sizeItemStateChanged
        // TODO add your handling code here:
        String str = (String)select_font_style.getSelectedItem().toString();
        int size = parseInt((String)select_font_size.getSelectedItem().toString());
        code_editor.setFont(new Font(str,Font.PLAIN,size));
    }//GEN-LAST:event_select_font_sizeItemStateChanged

    private void select_font_styleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_select_font_styleItemStateChanged
        // TODO add your handling code here:        
        String str = (String)select_font_style.getSelectedItem().toString();
        int size = parseInt((String)select_font_size.getSelectedItem().toString());
        code_editor.setFont(new Font(str,Font.PLAIN,size));
    }//GEN-LAST:event_select_font_styleItemStateChanged

    private void questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionActionPerformed
        try {
            // TODO add your handling code here:
            dout.writeUTF(question.getText());
            dout.writeInt(2);
//System.out.println(code_editor.getText());
            dout.flush();
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }//GEN-LAST:event_questionActionPerformed

    private void message_areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_message_areaMouseClicked
        // TODO add your handling code here:
        message_area.setText("");
    }//GEN-LAST:event_message_areaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        st = true;
        
        Thread t1;
        t1 = new Thread(){
            
            public void run()
            {
                while(true)
                {
                    if(st==true){
                        try
                        {
                            sleep(1000);
                            sec++;
//                            if(ms>=999)
//                            {
//                                sleep(1);
//                                ms=0;
//                                sec++;
//                            }
                            if(sec==60)
                            {
                                ms=0;
                                sec=0;
                                mins++;
                            }
                            if(mins==60)
                            {
                                ms=0;
                                sec=0;
                                mins=0;
                                hrs++;
                            }
                            seconds.setText(" : "+sec);
                            minutes.setText(" : "+mins);
                            hours.setText(""+hrs);
                        }
                        catch(Exception e){
                        }
                    }
                    else
                    {
                        break;
                    }
                }
            }
        };
        t1.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        st=false;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        st=false;
        ms=0;
        hrs=0;
        sec=0;
        mins=0;
        
        seconds.setText(": "+sec);
        minutes.setText(": "+mins);
        hours.setText(""+hrs);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public void func() throws IOException{
       try{//ss=new ServerSocket(6669);
     //  s=new Socket("172.29.43.151",6668);
             // s=new Socket("localhost",6668);
       //System.out.println("inside func");
       dis=new DataInputStream(s.getInputStream());
       while(true){
       //System.out.println("inf"); 
       str=(String)dis.readUTF();  
       int area = dis.readInt();
       //System.out.println("message= "+str);
       //code_editor.setEditorKit(new HTMLEditorKit());
       if(area==0)
       code_editor.setText(str);
       else if(area==1)
       {
           message_display_area.setText(message_display_area.getText() + "\n" + str);
       }
//       str=(String)dis.readUTF();  
//       System.out.println("message= "+str); 
//       jTextArea1.setText(str);
//       str=(String)dis.readUTF();  
//       System.out.println("message= "+str); 
//       jTextArea1.setText(str);
       }
    //ss.close();  
}catch(Exception e){System.out.println(e);} 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Screen().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane code_editor;
    private javax.swing.JButton compile_btn;
    private javax.swing.JLabel hours;
    private javax.swing.JTextArea input_text_tab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JTextField message_area;
    private javax.swing.JTextArea message_display_area;
    private javax.swing.JLabel minutes;
    private javax.swing.JTextArea notes;
    private javax.swing.JTextField notes_text;
    private javax.swing.JTextArea output_text_tab;
    private javax.swing.JTextField question;
    private javax.swing.JButton run_btn;
    private javax.swing.JButton save_notes_btn;
    private javax.swing.JLabel seconds;
    private javax.swing.JComboBox<String> select_font_size;
    private javax.swing.JComboBox<String> select_font_style;
    private javax.swing.JComboBox<String> select_language;
    private javax.swing.JButton send_btn;
    private javax.swing.JTextField studentName;
    // End of variables declaration//GEN-END:variables

private class Mthread extends Thread{
    @Override
    public void run(){
        try {
            func();
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }
    
}
